### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tgulacsi** [omerh/fcompare#2]
https://github.com/omerh/fcompare/blob/9985c4ba2dd652f28809e9e75b37d0daa31cccb4/main.go#L18
What is the filesInfo type for? You don't use it!

https://github.com/omerh/fcompare/blob/9985c4ba2dd652f28809e9e75b37d0daa31cccb4/main.go#L53
Why pointer? The fileInfo struct occupies only a handful of words, copying it is cheaper than dereferencing the pointer.
Why not allocate the []fileInfo properly - you know its probable size:
```filesInformation := make([]fileInfo, 0, len(files))```

https://github.com/omerh/fcompare/blob/9985c4ba2dd652f28809e9e75b37d0daa31cccb4/main.go#L56
```if !file.Mode().IsRegular() { continue }```

https://github.com/omerh/fcompare/blob/9985c4ba2dd652f28809e9e75b37d0daa31cccb4/main.go#L68
```for _, s := range filesInformation```

https://github.com/omerh/fcompare/blob/9985c4ba2dd652f28809e9e75b37d0daa31cccb4/main.go#L84
Why do you remove it? Your outer iteration is over it, your inner `compareFilesSlice` is not , but this line is here for its shadowing side effect, not what's written!

By the way, this algorithm is quite inefficient: you hash the files at least twice - at least cache the hash value into fileInfo (which can be a pointer in this case, or re-add it to the map after filling the cache),
and use a `map[int64][]fileInfo` to group fileInfos by size.

**Comment by omerh** [comment]
@tgulacsi thanks for your inputs, I made a complete refactor.
Feel free to comment

**Comment by tgulacsi** [comment]
I see you haven't read it.

**Comment by omerh** [comment]
removed the use of pointer
removed unneeded struct.
removed the 2 iterations to one for loop

care to review the refactoring ?
